# Generated by Django 3.1 on 2020-12-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('type', models.CharField(blank=True, max_length=50, unique=True)),
                ('about', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
