# Generated by Django 3.1 on 2020-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
