# Generated by Django 3.1 on 2020-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20201218_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='intro',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
